apiVersion: v1
kind: Service
metadata:
  name: flask-demo
  namespace: kubelab
spec:
  selector:
    app: flask-demo
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
